networks:
  app-network: {}

volumes:
  wp:
   driver: local
   driver_opts:
     type: none
     o: bind
     device: ${WP_VOLUME}
  db:
   driver: local
   driver_opts:
     type: none
     o: bind
     device: ${MDB_VOLUME}

secrets:
  db_password:
    file: ${SECRETS}/db_user_password.txt
  db_root_password:
    file: ${SECRETS}/db_root_password.txt
  ftp_password:
    file: ${SECRETS}/ftp_user_password.txt
  
services:
  nginx:
    container_name: nginx
    build: 
      context: 
        ${NGINX_PATH}
      args:
        BASE_DIGEST:        ${ALPINE_DIGEST}
        NGINX_PORT:         ${NGINX_PORT}
        NGINX_SCRIPT:       ${SCRIPTS}
    image: nginx
    environment:
      - NGINX_PORT
      - DOMAIN_NAME
      - NGINX_BDIR
      - SSL_PATH
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - wp:/var/www/html
    networks:
      - ${NETWORK}
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build:
      context:
        ${WORDPRESS_PATH}
      args:
        BASE_DIGEST:      ${ALPINE_DIGEST}
        WP_PORT:          ${WORDPRESS_PORT}
        WP_SCRIPT:        ${SCRIPTS}
        WP_CONF:          ${CONF}
        PHP_VERSION:      ${PHP_VERSION}
    image: wordpress
    secrets:
      - db_password
      - db_root_password
    environment:
      - WP_DB=${MYSQL_DATABASE}
      - WP_TITLE
      - WP_DB_USER=${MYSQL_USER}
      - WP_DB_ADMIN=${MYSQL_ROOT}
      - WP_DB_USER_PASS_FILE=/run/secrets/db_password
      - WP_DB_ROOT_PASS_FILE=/run/secrets/db_root_password
      - WP_HOST
      - WP_CHARSET
      - WP_PREFIX
      - WP_DEBUG
      - WP_VERSION
      - DOMAIN_NAME
      - PHP_VERSION
    expose:
      - "${WORDPRESS_PORT}"
    volumes:
      - wp:/var/www/html
    networks:
      - ${NETWORK}
    depends_on:
      - mariadb
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    build:
      context:
        ${MARIADB_PATH}
      args:
        BASE_DIGEST:      ${ALPINE_DIGEST}
        MARIADB_PORT:     ${MARIADB_PORT}
        MARIADB_SCRIPT:   ${SCRIPTS}
    image: mariadb
    secrets:
      - db_password
      - db_root_password
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_USER_PASSWORD_FILE=/run/secrets/db_password
      - MYSQL_ROOT
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MARIADB_PORT
      - MYSQL_DATADIR
    expose:
      - "${MARIADB_PORT}"
    volumes:
      - db:/var/lib/mysql
    networks:
      - ${NETWORK}
    restart: unless-stopped
